import { Product } from './types/Product'

export const sampleProducts: Product[] = [
  {
    name: 'Puma slim shirt',
    slug: 'puma-slim-shirt',
    category: 'Shirts',
    image: '../images/p1.jpg',
    price: 520,
    countInStock: 9,
    brand: 'Puma',
    rating: 4.5,
    numReviews: 10,
    description: 'high quality shirt',
  },
  {
    name: 'Adidas slim shirt',
    slug: 'adidas-slim-shirt',
    category: 'Shirts',
    image: '../images/p2.jpg',
    price: 520,
    countInStock: 9,
    brand: 'Puma',
    rating: 4.5,
    numReviews: 10,
    description: 'high quality shirt',
  },
  {
    name: 'Reebok slim shirt',
    slug: 'reebok-slim-shirt',
    category: 'Shirts',
    image: '../images/p3.jpg',
    price: 520,
    countInStock: 9,
    brand: 'Puma',
    rating: 4.5,
    numReviews: 10,
    description: 'high quality shirt',
  },
  {
    name: 'Nike slim shirt',
    slug: 'nike-slim-shirt',
    category: 'Shirts',
    image: '../images/p4.jpg',
    price: 520,
    countInStock: 9,
    brand: 'Puma',
    rating: 4.5,
    numReviews: 10,
    description: 'high quality shirt',
  },
]
